name: Ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: ruff-action
      uses: astral-sh/ruff-action@v3.0.1
      with:
        python-version: ${{ matrix.python-version }}


